version: '3.8'

services:
  db:
    image: mysql:8.4.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp_network

  wordpress:
    image: wordpress:latest
    ports:
      - "8089:80"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wp_network

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/mysql_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/wordpress_data
      o: bind

networks:
  wp_network: