apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-hello-world
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-hello-world
  template:
    metadata:
      labels:
        app: django-hello-world
    spec:
      containers:
      - name: django-hello-world
        image: openrc/django-hello-world-scoreboard:latest
        ports:
        - containerPort: 8000