apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: testing
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
