apiVersion: v1
kind: Service
metadata:
  name: django-hello-world
  namespace: testing
spec:
  type: NodePort
  selector:
    app: django-hello-world
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31007