apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storageclass
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
